export interface Payment {
  payment_id: number
  pawn_id: number
  session_id: number
  interest_amount: string       // NUMERIC as string
  custody_amount: string        // NUMERIC as string
  principal_amount: string      // NUMERIC as string
  total: string                 // GENERATED by DB: interest + custody + principal
  payment_type: 'interest' | 'redemption' | 'partial'
  payment_method: 'cash' | 'transfer' | 'qr'
  paid_at: string               // ISO 8601 timestamptz
  customer_name: string | null  // JOIN customers via pawns — null if pawn has no customer
}

export interface PaymentForVoucher {
  payment_id: number
  pawn_id: number
  payment_type: 'interest' | 'redemption' | 'partial'
  paid_at: string
  pawn_due_date: string
  customer_name: string
  customer_id_number: string
  months_paid: number
}

export interface CreatePaymentDto {
  pawn_id:           number
  months_paid:       number
  principal_amount?: number     // >= 0, defaults to 0 (redemption only)
  payment_type:      'interest' | 'redemption' | 'partial'
  payment_method?:   'cash' | 'transfer' | 'qr'
}
