export interface Payment {
  payment_id: number
  pawn_id: number
  session_id: number
  interest_amount: string       // NUMERIC as string
  custody_amount: string        // NUMERIC as string
  principal_amount: string      // NUMERIC as string
  total: string                 // GENERATED by DB: interest + custody + principal
  payment_type: 'interest' | 'redemption' | 'partial'
  payment_method: 'cash' | 'transfer' | 'qr'
  paid_at: string               // ISO 8601 timestamptz
  customer_name: string | null  // JOIN customers via pawns — null if pawn has no customer
}

export interface CreatePaymentDto {
  pawn_id: number
  interest_amount?: number      // >= 0, defaults to 0
  custody_amount?: number       // >= 0, defaults to 0
  principal_amount?: number     // >= 0, defaults to 0
  payment_type: 'interest' | 'redemption' | 'partial'
  payment_method?: 'cash' | 'transfer' | 'qr'
}
