export interface CashSession {
  session_id: number
  user_id: number
  cashier_name?: string        // joined from users.full_name — present in findAll()
  opening_amount: string       // NUMERIC returned as string by pg driver
  closing_amount: string | null
  expected_amount: string | null
  difference: string | null    // GENERATED by DB — never written by app
  status: 'open' | 'closed'
  opened_at: string            // ISO 8601 timestamptz
  closed_at: string | null
}

export interface OpenSessionDto {
  opening_amount: number       // >= 0
}

export interface CloseSessionDto {
  closing_amount: number       // >= 0
}
